### ISSUE TITLE
Link to framework in README

### ISSUE THREAD

**Issue by sbenthall** [machine-intelligence/research-forum#70]
You appear to be using an unusual web framework for this site.

It would be helpful for the onboarding on new (software) contributors if you documented in the README what framework you are using and how you can find out more information about it.

**Comment by malob** [comment]
The site is build in [Arc](arclanguage.org)

**Comment by malob** [comment]
Done in this [commit](https://github.com/machine-intelligence/research-forum/commit/f0ac3ec62bb87d345486cd13480b068611b3bd39).
